### ISSUE TITLE
kafka yaml 파일 실행 시 오류

### ISSUE THREAD

**Issue by hamsunwoo** [Team1-TU-tech/semi_final#10]
오류메세지
```python
kafka-producer  | Traceback (most recent call last):
kafka-producer  |   File "/app/pro.py", line 12, in <module>
kafka-producer  |     producer = KafkaProducer(
kafka-producer  |                ^^^^^^^^^^^^^^
kafka-producer  |   File "/usr/local/lib/python3.11/site-packages/kafka/producer/kafka.py", line 381, in __init__
kafka-producer  |     client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
kafka-producer  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kafka-producer  |   File "/usr/local/lib/python3.11/site-packages/kafka/client_async.py", line 244, in __init__
kafka-producer  |     self.config['api_version'] = self.check_version(timeout=check_timeout)
kafka-producer  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kafka-producer  |   File "/usr/local/lib/python3.11/site-packages/kafka/client_async.py", line 900, in check_version
kafka-producer  |     raise Errors.NoBrokersAvailable()
kafka-producer  | kafka.errors.NoBrokersAvailable: NoBrokersAvailable
```

**Comment by hamsunwoo** [comment]
```
Traceback (most recent call last):
  File "/app/pro.py", line 12, in <module>
    producer = KafkaProducer(
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
Traceback (most recent call last):
  File "/app/pro.py", line 12, in <module>
    producer = KafkaProducer(
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
Traceback (most recent call last):
  File "/app/pro.py", line 12, in <module>
    producer = KafkaProducer(
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
Traceback (most recent call last):
  File "/app/pro.py", line 12, in <module>
    producer = KafkaProducer(
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[DONE]: 1.4495995044708252
```

**Comment by hamsunwoo** [comment]
브로커보다 프로듀서가 먼저 켜져서 생기는 오류...
프로듀서는 연결이 실패하면 restart하는 옵션 추가하여 다시 시도하였을 땐 오류가 없음

**Comment by hamsunwoo** [comment]
https://medium.com/sjk5766/kafka-broker-3%EA%B0%9C%EB%A5%BC-%EC%B6%94%EC%B2%9C%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-79c18dcafaeb

**Comment by hamsunwoo** [comment]
- 해결
<img width="1586" alt="스크린샷 2024-11-12 10 00 52" src="https://github.com/user-attachments/assets/210bb6d1-af36-460d-9c21-24767918e062">

**Comment by hamsunwoo** [comment]
연결 실패할 경우,
<img width="1481" alt="스크린샷 2024-11-12 10 17 29" src="https://github.com/user-attachments/assets/ed0fc9b8-26cc-4e21-9347-4dcd64137396">
